// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/list_accounts.ts
import { createClient } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^4.4.3";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_accounts_default = defineTool({
  name: "list_accounts",
  title: "Listar contas",
  description: "Lista as contas financeiras (contas correntes, poupan\xE7a, cart\xF5es, etc.) do usu\xE1rio autenticado.",
  inputSchema: {
    include_inactive: z.boolean().optional().describe("Se true, inclui contas inativas.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ include_inactive }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("accounts").select("id,name,type,scope,institution,current_balance,initial_balance,credit_limit,closing_day,due_day,is_active,include_in_net_worth").order("name");
    if (!include_inactive) query = query.eq("is_active", true);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { accounts: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list_categories.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z2 } from "npm:zod@^4.4.3";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_categories_default = defineTool2({
  name: "list_categories",
  title: "Listar categorias",
  description: "Lista as categorias de receita, despesa e transfer\xEAncia do usu\xE1rio autenticado.",
  inputSchema: {
    kind: z2.enum(["expense", "income", "transfer"]).optional().describe("Filtra por tipo de categoria.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ kind }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    const supabase = supabaseForUser2(ctx);
    let query = supabase.from("categories").select("id,name,kind,color,icon,parent_id,is_system").order("name");
    if (kind) query = query.eq("kind", kind);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { categories: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list_transactions.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z3 } from "npm:zod@^4.4.3";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_transactions_default = defineTool3({
  name: "list_transactions",
  title: "Listar transa\xE7\xF5es",
  description: "Lista as transa\xE7\xF5es do usu\xE1rio autenticado, opcionalmente filtradas por intervalo de datas, tipo, conta ou categoria.",
  inputSchema: {
    from_date: z3.string().optional().describe("Data inicial no formato YYYY-MM-DD."),
    to_date: z3.string().optional().describe("Data final no formato YYYY-MM-DD."),
    type: z3.enum(["income", "expense", "transfer"]).optional(),
    account_id: z3.string().uuid().optional(),
    category_id: z3.string().uuid().optional(),
    limit: z3.number().int().positive().optional().describe("M\xE1ximo de registros (padr\xE3o 50, m\xE1ximo 500).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    const limit = Math.min(input.limit ?? 50, 500);
    const supabase = supabaseForUser3(ctx);
    let query = supabase.from("transactions").select("id,transaction_date,type,amount,status,notes,account_id,category_id,payee_id,payment_method,source").is("deleted_at", null).order("transaction_date", { ascending: false }).limit(limit);
    if (input.from_date) query = query.gte("transaction_date", input.from_date);
    if (input.to_date) query = query.lte("transaction_date", input.to_date);
    if (input.type) query = query.eq("type", input.type);
    if (input.account_id) query = query.eq("account_id", input.account_id);
    if (input.category_id) query = query.eq("category_id", input.category_id);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { transactions: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create_transaction.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z4 } from "npm:zod@^4.4.3";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var create_transaction_default = defineTool4({
  name: "create_transaction",
  title: "Criar transa\xE7\xE3o",
  description: "Cria uma nova transa\xE7\xE3o (receita, despesa ou transfer\xEAncia) para o usu\xE1rio autenticado.",
  inputSchema: {
    account_id: z4.string().uuid().describe("ID da conta associada (use list_accounts)."),
    type: z4.enum(["income", "expense", "transfer"]).describe("Tipo de transa\xE7\xE3o."),
    amount: z4.number().positive().describe("Valor positivo em BRL."),
    transaction_date: z4.string().describe("Data no formato YYYY-MM-DD."),
    category_id: z4.string().uuid().optional().describe("ID da categoria (use list_categories)."),
    notes: z4.string().optional().describe("Descri\xE7\xE3o/observa\xE7\xF5es."),
    status: z4.enum(["pending", "cleared", "reconciled"]).optional(),
    payment_method: z4.string().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    const supabase = supabaseForUser4(ctx);
    const { data, error } = await supabase.from("transactions").insert({
      user_id: ctx.getUserId(),
      account_id: input.account_id,
      type: input.type,
      amount: input.amount,
      transaction_date: input.transaction_date,
      category_id: input.category_id ?? null,
      notes: input.notes ?? null,
      status: input.status ?? "cleared",
      payment_method: input.payment_method ?? null,
      source: "mcp"
    }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Transa\xE7\xE3o criada: ${data.id}` }],
      structuredContent: { transaction: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "bockojhtmjrtfvkgfocf";
var mcp_default = defineMcp({
  name: "meu-cartaozinho-mcp",
  title: "Meu Cart\xE3ozinho",
  version: "0.1.0",
  instructions: "Ferramentas para o app de organiza\xE7\xE3o financeira. Use list_accounts, list_categories e list_transactions para consultar dados, e create_transaction para registrar novas transa\xE7\xF5es.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_accounts_default, list_categories_default, list_transactions_default, create_transaction_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
