// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { SUPABASE_ENV } from "./env";

const SUPABASE_URL = SUPABASE_ENV.url ?? "https://invalid-supabase-url.local";
const SUPABASE_KEY = SUPABASE_ENV.key ?? "invalid-supabase-key";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

if (!SUPABASE_ENV.isConfigured) {
  console.error("[Supabase] Invalid environment configuration.", {
    issues: SUPABASE_ENV.issues,
    keyName: SUPABASE_ENV.keyName,
    url: SUPABASE_ENV.url,
  });
} else {
  console.info("[Supabase] Environment loaded.", {
    keyName: SUPABASE_ENV.keyName,
    url: SUPABASE_ENV.url,
  });
}

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: "pkce",
  },
});

export const isSupabaseConfigured = SUPABASE_ENV.isConfigured;
export const supabaseEnvIssues = SUPABASE_ENV.issues;
export const supabaseKeyName = SUPABASE_ENV.keyName;